import React from 'react';
import { BsFillBriefcaseFill } from 'react-icons/bs';

const Experience = () => {
    return (
        <div className='my-24 pt-32' id='Experience'>
            <div className='md:flex justify-center items-center'>
                <div >
                    <div className='flex mx-auto  items-center text-xl w-[150px] rounded p-2 font-bold text-second bg-sec-bg'>
                        <span className='text-[20px'><BsFillBriefcaseFill></BsFillBriefcaseFill></span>
                        <h2 className='px-2 '>Experience</h2>
                    </div>
                    <div>
                        <h1 className='text-5xl font-bold py-4'>Trajectory until here</h1>
                    </div>
                </div>
            </div>
            <div className='md:flex w-full text-left md:text-center my-20' >
                <div className='w-full md:w-1/2'>
                    <h2 className='text-[32px] font-bold'>Professional Experience </h2>
                    <div className='md:mt-24'>
                        <div className='py-4 px-6 my-[32px] bg-[#14142a] md:w-[580px] rounded-lg text-left'>
                            <h2 className='text-[20px]  '>Information Technology Partners </h2>
                            <h2 className='text-[20px] font-bold '>Senior Software Engineer</h2>
                            <p className='py-4 text-[#ffffff8a]'>As a developer, I have experience developing applications using Agile methodology and implementing business logic with C# .NET. I have extensive front-end and back-end experience with the .NET Framework, MVC design pattern, and GUI web development using technologies like AJAX, jQuery, and Angular. I have also worked with ASP.NET server controls and utilized REST and SOAP web services. Additionally, I have performed various types of testing and used GIT for version control. I have worked with technologies such as .NET Framework, Angular, Kendo-UI, MS SQL, and Azure DevOps.</p>
                            <div className='flex justify-between text-[18px] py-4 text-second'>
                                <strong>Remote</strong>
                                <span>Sep 2021–Mar 2022</span>
                            </div>
                        </div>
                        <div className='py-4 px-6 my-[32px] border-4 border-[#14142a] md:w-[580px] rounded-lg text-left'>
                            <h2 className='text-[20px] '>Price Chopper</h2>
                            <h2 className='text-[20px] font-bold '>Software Engineer</h2>
                            <p className='py-4 text-[#ffffff8a]'>As a developer, my primary responsibilities included developing and implementing new features in the company's internal CRM. I was also responsible for identifying and fixing any bugs or integrity issues that arose within the system. Additionally, I worked on implementing and modifying the ecommerce system using Umbraco and Petapoco. To accomplish these tasks, I used a variety of technologies such as .NET Core, React, Umbraco, Razor, Knockout.js, and Petapoco.</p>
                            <div className='flex justify-between text-[18px] py-4 text-second'>
                                <strong>Remote</strong>
                                <span>Jan 2021–Sep2021</span>
                            </div>
                        </div>
                        <div className='py-4 px-6 my-[32px] border-4 border-[#14142a] md:w-[580px] rounded-lg text-left'>
                            <h2 className='text-[20px]  '>Luxury Puerto Rico Real Estate</h2>
                            <h2 className='text-[20px] font-bold '>Full stack Developer</h2>
                            <p className='py-4 text-[#ffffff8a]'>My primary responsibilities include designing and implementing software based on the requirements generated by the organization. This involves developing both the frontend and backend of the application and refining existing features while also creating new ones. You will need to develop SQL procedures, views, and other SQL components to support application functionality. After developing the application, you will deploy finished versions to various environments. Finally, as a developer, you will also be responsible for supporting the application by troubleshooting bugs and providing ongoing maintenance and support.</p>
                            <div className='flex justify-between text-[18px] py-4 text-second'>
                                <strong>Remote</strong>
                                <span>Feb 2019–Jan2021</span>
                            </div>
                        </div>
                        <div className='py-4 px-6 my-[32px] border-4 border-[#14142a] md:w-[580px] rounded-lg text-left'>
                            <h2 className='text-[20px]  '>Pico</h2>
                            <h2 className='text-[20px] font-bold '>Software Engineer</h2>
                            <p className='py-4 text-[#ffffff8a]'> I developed a web application that utilized AngularJS MVC Framework to bind retrieved data/model from a database through services in a controller to the view. I created and consumed services using WCF and also created service contracts and data contracts for the services. In addition, I created a data access layer for retrieving data from the database and used LINQ for database transactions. I created stored procedures, functions, triggers, and views in SQL server. Furthermore, I was heavily involved in integrating CRM with Quote Express, Lead Services, and Desking projects. To ensure the quality of the CRM, I built a framework using Selenium to perform automated testing.</p>
                            <div className='flex justify-between text-[18px] py-4 text-second'>
                                <strong>Local</strong>
                                <span>Jan 2016–Feb2019</span>
                            </div>
                        </div>
                    </div>
                </div>
                <div className='w-full md:w-1/2'>
                    <h2 className='text-[32px] font-bold'>Educational Experience </h2>
                    <div className='md:mt-24'>
                        <div className='py-4 px-6 my-[32px] bg-[#14142a] md:w-[580px] rounded-lg text-left'>
                            <h2 className='text-[20px] font-bold '>New Jersey Institute of Technology</h2>
                            <p className='py-4 text-[#ffffff8a]'>As a computer science graduate, I have gained a strong foundation in various programming languages, software development methodologies, data structures, algorithms, and computer systems. I am also have the ability to analyze and solve complex problems using technology and have acquired essential skills such as critical thinking, problem-solving, teamwork, and communication.</p>
                            <div className='flex justify-between text-[18px] py-4 text-second'>
                                <strong>Bachelor’s Degree, Computer Science</strong>
                                <span>2016 –Graduated</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Experience;